ui: mocha-bdd
browsers:
  - name: chrome
    version: -1..latest
  - name: firefox
    version: -1..latest
  - name: safari
    version: -1..latest
  - name: iphone
    version: '8.0..latest'
  - name: android
    version: 4.0..latest
